### ISSUE TITLE
Devis

### ISSUE THREAD

**Issue by b1nj** [ipsum3/reservation#3]
Possibilité de télécharger/créer un devis
https://www.economie.gouv.fr/dgccrf/Publications/Vie-pratique/Fiches-pratiques/Voyager-en-voiture-louer-vehicule

**Comment by ipanor** [comment]
ON part sur un pdf avec vue spécifique et modifiable dans le projet comme le contrat 
Mettre le moins de champs possible et la durée d'expiration configurable en admin (Mettre dans table settings)
(Pour la vue, se baser sur un bon de commande ex: bijouterie-qgc => Voir fichier devis modele)

**Comment by b1nj** [comment]
reference légale : https://www.legifrance.gouv.fr/loda/id/JORFTEXT000030375910
