### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by ipanor** [ipsum3/reservation#8]
Créer 2 tables sources et source_types et changer dans reservation le cham source en source_id (non utilisé)
Source :
- Nom (Site internet, Appel, Agence, Google ads, Emailing,...)
- type_id
- ref_tracking (pour avoir un lien spécifique)

Type :
- Nom (type : publicité, web, campagne marketing, direct,...)

Voir si on garde la trace de la ref tracking par session ou cookie (probleme rgpd)

**Comment by b1nj** [comment]
bug si une résa n'a pas de source. Ne rien mettre dans la liste déroulante source en admin

**Comment by ipanor** [comment]
Corrigé !
